__include__: [
  './dataset/coco_detection.yml',
  './runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd.yml',
]

#PResNet:
#  depth: 101
Backbone_VSSM:
  freeze_at: 0
  freeze_norm: True
  out_indices: [1, 2, 3]

HybridEncoder:
  # intra
  hidden_dim: 384
  dim_feedforward: 2048


RTDETRTransformer:
  feat_channels: [384, 384, 384]


optimizer:
  type: AdamW
  params: 
    - 
      params: 'backbone'
      lr: 0.000001